In [0]:
pip install tensorboardcolab

In [0]:
from tensorboardcolab import TensorBoardColab, TensorBoardColabCallback
tbc=TensorBoardColab()

Wait for 8 seconds...
TensorBoard link:
https://482d1da0.ngrok.io


In [1]:
from keras import Sequential
from keras import layers
from keras import optimizers

from keras.callbacks import ModelCheckpoint
from keras.callbacks import ReduceLROnPlateau

Using TensorFlow backend.


In [0]:
import warnings
warnings.filterwarnings('ignore')

In [0]:
import numpy as np
from sklearn.metrics import accuracy_score
import string

In [0]:
def create_labels(paragraph, hashmap):
    # paragraph = paragraph.lower()
    output = []
    for i in paragraph:
        output.append(list(map(int,str(hashmap[i]))))
    
    return np.array(output)


In [0]:
para = " ab b a"
hashmap = {'x': 10001100, '^': 11010110, '@': 11100001, ')': 10100000, ' ': 10011000, '+': 10010100,
 '4': 10001011, 'M': 10100011,
  '-': 10001010, 'd': 11001111, 'F': 10111000, '/': 10111110, 'C': 11101111, 'm': 10100111,
   'S': 10111111, '=': 11101110, '<': 11010001, '`': 10110001, '%': 11001001, 'e': 10001110,
           '"': 11011010, '&': 10000111, 'p': 11000100, '>': 11000011, 'v': 10010000, 'q': 10010110, 'H': 10100100,
           '$': 11100110, 'T': 10000110, ':': 10100001, 'B': 11100011, 'R': 10110011, '?': 11010000, '6': 11101101, 'V': 11110100, '2': 11001011, 't': 10010111, 'D': 10001000, 'W': 11101100, '3': 11101010, 'J': 11111111, 'g': 11111011, '.': 11011101, 'O': 10001101, '!': 11100101, 'L': 10010011,
    ']': 11011011, 'I': 10111101, 'y': 11000001, 'X': 10000011, 'j': 10111010, 'Z': 10101101, ',': 11111101,
           'h': 11011111, '_': 11010111, 'P': 11001110, '0': 11101011, 'k': 10111011, 'a': 10101001, 'r': 11110001, '\\': 11000000, 'Y': 10110000, 'l': 10110111, 'b': 11110000, 'z': 10101111, 's': 11001101, ';': 11110010, 'c': 11110111, 'U': 10000101, '[': 11001010, 'o': 11101001, 'N': 10100101, '1': 11001000, '7': 10011011, 'f': 10101100, 'G': 10111001, 'A': 10111100, 'n': 10000100, '5': 11000111, 'E': 10100010, '9': 11100010, 'Q': 11110011,
     "'": 10011100, 'w': 11111110, 'i': 11001100, '8': 11100111, '#': 11011000, 'K': 10011101, '(': 10011111, 'u': 10011001, '*': 11100100}


In [6]:
print(len(hashmap))

91


In [7]:
Y_train = create_labels(para, hashmap)
print(Y_train.shape)
print(Y_train[0])

(7, 8)
[1 0 0 1 1 0 0 0]


In [0]:
# def create_input_array(word):
#     arrmain = []
#     for letter in word:
#         if(letter != ' '):
#             arr = np.zeros(27)
#             index = ord(letter) - 97
#             arr[index] += 1
#             arrmain.append(arr)
#         else:
#             arr = np.zeros(27)
#             index2 = ord(' ') - 6
#             arr[index2] += 1
#             arrmain.append(arr)
#     return(np.array(arrmain))


In [8]:
characters = [chr(i) for i in range(32, 123)]
print(sorted(characters))
print(ord(' '))
print(ord('z'))

[' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '^', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
32
122


In [0]:
def create_input_array(word):
    enc_l = []
    for i in word:
        arr = np.zeros(91)
        enc = ord(i) - 32
#         print(enc)
        arr[enc] += 1
        enc_l.append(arr)
    return(np.array(enc_l))

In [10]:
w = 'ab c'
inp_arr = create_input_array(w)
print(inp_arr)
print(inp_arr.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0

In [0]:
X_train_string = "tnfhie zjtgv tqimu ewh hmkze khd deawo yjxving vhp rmcid mwgpby xyib hesl gzrsuvx uqw bkqgv sndwgbc qnbzs ykziwhj tozxe qsdfb hqni izjr dkcexn umpgnfq ucfqbox aozhfyb eputyvf hjzerv zcdtl kxvu mupa ibned dqkmr kqiop jiamwr miq eua xhsnc xvizcfy wdnahkm fgjrpyt ldtu cvhnfg duasjwi hfmlvow cuompn gnjtbxv adhc ebfg wtaznb skrmx yuhw vzempa jbacx qkgxnbi ymret pbjqd pvzkq oanbc fag dlwubxv csxtwv vnmew rmzykc emqr elqtbcm wbgpyoc qdgi nlyadu obaih qvhspz uskh psk fovkerl ksut ulpr dxclpm xku kdenia ricu cron hfdz aszxvmd xow kpawin ydcv sbnqpjv ajr smyz dft afeg cam gmu dcb dtihyr kzra oxfqwb jsxtrb odbewy jvo qcx "

In [12]:
X_train = create_input_array(X_train_string)
print(X_train.shape)

(618, 91)


In [13]:
print(X_train[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [14]:
Y_train = create_labels(X_train_string, hashmap)
print(Y_train.shape)

(618, 8)


In [15]:
print(Y_train)
print(Y_train.shape)

[[1 0 0 ... 1 1 1]
 [1 0 0 ... 1 0 0]
 [1 0 1 ... 1 0 0]
 ...
 [1 1 1 ... 1 1 1]
 [1 0 0 ... 1 0 0]
 [1 0 0 ... 0 0 0]]
(618, 8)


In [0]:
model = Sequential()
model.add(layers.Dense(91, input_shape = (91,)))
model.add(layers.LeakyReLU())


model.add(layers.Dense(64))
model.add(layers.LeakyReLU())

model.add(layers.Dense(32))
model.add(layers.LeakyReLU())

model.add(layers.Dense(32))
model.add(layers.LeakyReLU())

model.add(layers.Dense(16))
model.add(layers.LeakyReLU())

model.add(layers.Dense(8))
model.add(layers.LeakyReLU())

In [0]:
learning_rate = 0.045
epochs = 10
batch_size = None

In [0]:
optim = optimizers.Adam(lr = learning_rate) 

In [0]:
checkpoint = ModelCheckpoint('/content/encrypt_1.h5', monitor = 'val_loss', verbose = 1, save_best_only = True, save_weights_only = True)
reducelr = ReduceLROnPlateau(monitor = 'val_loss', verbose = 1, patience = 5,factor = 0.05, min_lr = 0.003)

In [21]:
model.compile(optimizer = optim, loss = 'mean_squared_error', metrics = ['acc'])

In [22]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 91)                8372      
_________________________________________________________________
leaky_re_lu_7 (LeakyReLU)    (None, 91)                0         
_________________________________________________________________
dense_8 (Dense)              (None, 64)                5888      
_________________________________________________________________
leaky_re_lu_8 (LeakyReLU)    (None, 64)                0         
_________________________________________________________________
dense_9 (Dense)              (None, 32)                2080      
_________________________________________________________________
leaky_re_lu_9 (LeakyReLU)    (None, 32)                0         
_________________________________________________________________
dense_10 (Dense)             (None, 32)               

In [24]:
history = model.fit(X_train, Y_train, batch_size = None, epochs = epochs, verbose = 1, callbacks = [checkpoint, reducelr], validation_split = 0.1)



Train on 556 samples, validate on 62 samples
Epoch 1/10
556/556 [==============================] - 4s 8ms/step - loss: 0.2460 - acc: 0.4892 - val_loss: 0.1432 - val_acc: 0.1129

Epoch 00001: val_loss improved from inf to 0.14318, saving model to /content/encrypt_1.h5
Epoch 2/10
556/556 [==============================] - 0s 196us/step - loss: 0.0901 - acc: 0.4029 - val_loss: 0.0713 - val_acc: 0.2742

Epoch 00002: val_loss improved from 0.14318 to 0.07131, saving model to /content/encrypt_1.h5
Epoch 3/10
556/556 [==============================] - 0s 196us/step - loss: 0.0350 - acc: 0.3094 - val_loss: 0.0363 - val_acc: 0.2419

Epoch 00003: val_loss improved from 0.07131 to 0.03625, saving model to /content/encrypt_1.h5
Epoch 4/10
556/556 [==============================] - 0s 199us/step - loss: 0.0268 - acc: 0.2086 - val_loss: 0.0194 - val_acc: 0.1935

Epoch 00004: val_loss improved from 0.03625 to 0.01939, saving model to /content/encrypt_1.h5
Epoch 5/10
556/556 [=======================

In [0]:
output = model.predict(X_train)

In [26]:
print(output[0])

[ 9.9578130e-01 -9.5213956e-04 -1.7695786e-03  9.8024845e-01
 -3.2474578e-03  9.8037529e-01  9.9418986e-01  9.8524410e-01]


In [27]:
print(Y_train[0])

[1 0 0 1 0 1 1 1]


In [28]:
print(output.shape)

(618, 8)


In [0]:
def change_output(arr):
    '''' Rounding off the confident outputs '''
    row=arr.shape[0]
    col=arr.shape[1]
    for i in range(row):
      for j in range(col):
        if(arr[i][j]>0.5):
          arr[i][j]=1
        else:
          arr[i][j]=0
          
    arr.astype('int')
    return(arr)    

In [0]:
def accuracy(Y_pred, Y_train):
    ''' Given the predicted array, it compares it with the hashmap and gives the accuracy score '''
    Y_pred_int = change_output(Y_pred)
    print("Accuracy for the given batch is :", accuracy_score(Y_pred, Y_train) * 100 , " % ")

In [31]:
Y_pred = model.predict(X_train)
accuracy(Y_pred, Y_train)

Accuracy for the given batch is : 100.0  % 


In [32]:
print(Y_train.shape)

(618, 8)


In [0]:
decrypter = Sequential()

decrypter.add(layers.Dense(16, input_shape = (8,)))
decrypter.add(layers.LeakyReLU())

decrypter.add(layers.Dense(32))
decrypter.add(layers.LeakyReLU())

decrypter.add(layers.Dense(64))
decrypter.add(layers.LeakyReLU())

decrypter.add(layers.Dense(64))
decrypter.add(layers.LeakyReLU())

decrypter.add(layers.Dense(91))
decrypter.add(layers.LeakyReLU())


In [0]:
learning_rate = 0.045
epochs = 10
batch_size = None

In [0]:
decrypter_optimizer = optimizers.Adam(lr = learning_rate)

In [0]:
decrypter.compile(optimizer=decrypter_optimizer, loss = 'mean_squared_error', metrics = ['acc'])

In [0]:
decrypter_X_train = Y_train
decrypter_Y_train = X_train

In [50]:
print(decrypter_X_train.shape)
print(decrypter_Y_train.shape)

(618, 8)
(618, 91)


In [0]:
checkpoint = ModelCheckpoint('/content/denrypt_1.h5', monitor = 'val_loss', verbose = 1, save_best_only = True, save_weights_only = True)
reducelr = ReduceLROnPlateau(monitor = 'val_loss', verbose = 1, patience = 5,factor = 0.05, min_lr = 0.003)

In [52]:
decrypter_history = decrypter.fit(decrypter_X_train, decrypter_Y_train,
                              batch_size = None,
                              epochs = epochs, verbose = 1,
                              callbacks = [checkpoint, reducelr],
                              validation_split = 0.1)

Train on 556 samples, validate on 62 samples
Epoch 1/10
556/556 [==============================] - 0s 831us/step - loss: 0.0158 - acc: 0.5216 - val_loss: 0.0088 - val_acc: 0.5645

Epoch 00001: val_loss improved from inf to 0.00880, saving model to /content/denrypt_1.h5
Epoch 2/10
556/556 [==============================] - 0s 167us/step - loss: 0.0070 - acc: 0.7392 - val_loss: 0.0047 - val_acc: 0.9516

Epoch 00002: val_loss improved from 0.00880 to 0.00469, saving model to /content/denrypt_1.h5
Epoch 3/10
556/556 [==============================] - 0s 164us/step - loss: 0.0037 - acc: 0.9640 - val_loss: 0.0027 - val_acc: 1.0000

Epoch 00003: val_loss improved from 0.00469 to 0.00274, saving model to /content/denrypt_1.h5
Epoch 4/10
556/556 [==============================] - 0s 167us/step - loss: 0.0020 - acc: 1.0000 - val_loss: 0.0014 - val_acc: 1.0000

Epoch 00004: val_loss improved from 0.00274 to 0.00137, saving model to /content/denrypt_1.h5
Epoch 5/10
556/556 [=======================

In [0]:
decrypted_text = decrypter.predict(decrypter_X_train)

In [0]:
decrypted_int_text = change_output(decrypted_text)

In [55]:
print(decrypted_text[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [56]:
print(decrypted_int_text[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [57]:
print(decrypter_Y_train[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [58]:
print(np.argmax(decrypted_text[0]))

84


In [59]:
print(np.argmax(decrypter_Y_train[0]))

84


In [60]:
print(decrypted_text[1])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [61]:
print(decrypted_int_text[1])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [62]:
print(decrypter_Y_train[1])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [63]:
print(np.argmax(decrypted_text[1]))

78


In [64]:
print(np.argmax(decrypter_Y_train[1]))

78


In [65]:
accuracy(decrypted_int_text, decrypter_Y_train)

Accuracy for the given batch is : 100.0  % 
