In [185]:
pip install tensorboardcolab

In [186]:
from tensorboardcolab import TensorBoardColab, TensorBoardColabCallback
tbc=TensorBoardColab()

Wait for 8 seconds...
TensorBoard link:
https://482d1da0.ngrok.io


In [0]:
from keras import Sequential
from keras import layers
from keras import optimizers
from keras.callbacks import ModelCheckpoint
from keras.callbacks import ReduceLROnPlateau

In [0]:
import warnings
warnings.filterwarnings('ignore')

In [0]:
import numpy as np
from sklearn.metrics import accuracy_score

In [0]:
def create_labels(paragraph, hashmap):
    paragraph = paragraph.lower()
    output = []
    for i in paragraph:
        output.append(list(map(int,str(hashmap[i]))))
    
    return np.array(output)


In [0]:
para = " ab b a"

hashmap = {'z': 110001, 't': 101110, 'd': 111010, 'a': 111110, 'h': 100111, 'f': 101111, 'o': 101100, 'y': 110101, 'b': 111111, 'l': 111101, ' ': 100110, 'k': 111100, 'n': 110100,
           'w': 100001, 'q': 111001, 'p': 100100, 'g': 101010, 'x': 101001, 'i': 110110, 'v': 101011, 'c': 101101, 'm': 111000, 'e': 111011, 'r': 110010, 's': 110000, 'j': 100101, 'u': 101000}


In [235]:
Y_train = create_labels(para, hashmap)
print(Y_train.shape)

(7, 6)


In [0]:
def create_input_array(word):
    arrmain = []
    for letter in word:
        if(letter != ' '):
            arr = np.zeros(27)
            index = ord(letter) - 97
            arr[index] += 1
            arrmain.append(arr)
        else:
            arr = np.zeros(27)
            index2 = ord(' ') - 6
            arr[index2] += 1
            arrmain.append(arr)
    return(np.array(arrmain))


In [237]:
w = 'ab c'
inp_arr = create_input_array(w)
print(inp_arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0.]]


In [0]:
X_train_string = "tnfhie zjtgv tqimu ewh hmkze khd deawo yjxving vhp rmcid mwgpby xyib hesl gzrsuvx uqw bkqgv sndwgbc qnbzs ykziwhj tozxe qsdfb hqni izjr dkcexn umpgnfq ucfqbox aozhfyb eputyvf hjzerv zcdtl kxvu mupa ibned dqkmr kqiop jiamwr miq eua xhsnc xvizcfy wdnahkm fgjrpyt ldtu cvhnfg duasjwi hfmlvow cuompn gnjtbxv adhc ebfg wtaznb skrmx yuhw vzempa jbacx qkgxnbi ymret pbjqd pvzkq oanbc fag dlwubxv csxtwv vnmew rmzykc emqr elqtbcm wbgpyoc qdgi nlyadu obaih qvhspz uskh psk fovkerl ksut ulpr dxclpm xku kdenia ricu cron hfdz aszxvmd xow kpawin ydcv sbnqpjv ajr smyz dft afeg cam gmu dcb dtihyr kzra oxfqwb jsxtrb odbewy jvo qcx "

In [241]:
X_train = create_input_array(X_train_string)
print(X_train.shape)

(618, 27)


In [242]:
print(X_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [243]:
Y_train = create_labels(X_train_string, hashmap)
print(Y_train.shape)

(618, 6)


In [244]:
print(Y_train)

[[1 0 1 1 1 0]
 [1 1 0 1 0 0]
 [1 0 1 1 1 1]
 ...
 [1 0 1 1 0 1]
 [1 0 1 0 0 1]
 [1 0 0 1 1 0]]


In [0]:
model = Sequential()
model.add(layers.Dense(27, input_shape = (27,)))
model.add(layers.LeakyReLU())

model.add(layers.Dense(32))
model.add(layers.LeakyReLU())

model.add(layers.Dense(32))
model.add(layers.LeakyReLU())

model.add(layers.Dense(16))
model.add(layers.LeakyReLU())

model.add(layers.Dense(6))
model.add(layers.LeakyReLU())

In [0]:
learning_rate = 0.045
epochs = 50
batch_size = None

In [0]:
optim = optimizers.Adam(lr = learning_rate) 

In [0]:
checkpoint = ModelCheckpoint('/content/encrypt_1.h5', monitor = 'val_loss', verbose = 1, save_best_only = True, save_weights_only = True)
reducelr = ReduceLROnPlateau(monitor = 'val_loss', verbose = 1, patience = 5,factor = 0.05, min_lr = 0.003)

In [0]:
model.compile(optimizer = optim, loss = 'mean_squared_error', metrics = ['acc'])

In [221]:
model.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_34 (Dense)             (None, 27)                756       
_________________________________________________________________
leaky_re_lu_28 (LeakyReLU)   (None, 27)                0         
_________________________________________________________________
dense_35 (Dense)             (None, 32)                896       
_________________________________________________________________
leaky_re_lu_29 (LeakyReLU)   (None, 32)                0         
_________________________________________________________________
dense_36 (Dense)             (None, 32)                1056      
_________________________________________________________________
leaky_re_lu_30 (LeakyReLU)   (None, 32)                0         
_________________________________________________________________
dense_37 (Dense)             (None, 16)              

In [222]:
history = model.fit(X_train, Y_train, batch_size = None, epochs = epochs, verbose = 1, callbacks = [checkpoint,TensorBoardColabCallback(tbc), reducelr], validation_split = 0.1)

Train on 556 samples, validate on 62 samples
Epoch 1/50
556/556 [==============================] - 0s 514us/step - loss: 0.1657 - acc: 0.5773 - val_loss: 0.0298 - val_acc: 0.3226

Epoch 00001: val_loss improved from inf to 0.02984, saving model to /content/encrypt_1.h5
Epoch 2/50
556/556 [==============================] - 0s 198us/step - loss: 0.0252 - acc: 0.2824 - val_loss: 0.0131 - val_acc: 0.5968

Epoch 00002: val_loss improved from 0.02984 to 0.01307, saving model to /content/encrypt_1.h5
Epoch 3/50
556/556 [==============================] - 0s 122us/step - loss: 0.0093 - acc: 0.2878 - val_loss: 0.0060 - val_acc: 0.3226

Epoch 00003: val_loss improved from 0.01307 to 0.00599, saving model to /content/encrypt_1.h5
Epoch 4/50
556/556 [==============================] - 0s 134us/step - loss: 0.0038 - acc: 0.2428 - val_loss: 0.0026 - val_acc: 0.2097

Epoch 00004: val_loss improved from 0.00599 to 0.00262, saving model to /content/encrypt_1.h5
Epoch 5/50
556/556 [=======================

In [0]:
output = model.predict(X_train)

In [228]:
print(output[0])

[1.0001807e+00 1.1652708e-05 1.0000263e+00 9.9995279e-01 9.9997157e-01
 6.8247318e-06]


In [229]:
print(Y_train[0])

[1 0 1 1 1 0]


In [224]:
print(output.shape)

(618, 6)


In [0]:
def change_output(arr):
    '''' Rounding off the confident outputs '''
    row=arr.shape[0]
    col=arr.shape[1]
    for i in range(row):
      for j in range(col):
        if(arr[i][j]>0.5):
          arr[i][j]=1
        else:
          arr[i][j]=0
          
    arr.astype('int')
    return(arr)    

In [0]:
def accuracy(Y_pred, Y_train):
    ''' Given the predicted array, it compares it with the hashmap and gives the accuracy score '''
    Y_pred_int = change_output(Y_pred)
    print("Accuracy for the given batch is :", accuracy_score(Y_pred, Y_train) * 100 , " % ")

In [227]:
Y_pred = model.predict(X_train)
accuracy(Y_pred, Y_train)

Accuracy for the given batch is : 100.0  % 


In [75]:
print(Y_train.shape)

(618, 6)


In [0]:
decrypter = Sequential()

decrypter.add(layers.Dense(50, input_shape = (6,)))
decrypter.add(layers.LeakyReLU())

decrypter.add(layers.Dense(40))
decrypter.add(layers.LeakyReLU())

decrypter.add(layers.Dense(30))
decrypter.add(layers.LeakyReLU())

decrypter.add(layers.Dense(27))
decrypter.add(layers.LeakyReLU())


In [0]:
learning_rate = 0.045
epochs = 500
batch_size = None

In [0]:
decrypter_optimizer = optimizers.Adam(lr = learning_rate)

In [0]:
decrypter.compile(optimizer=decrypter_optimizer, loss = 'mean_squared_error', metrics = ['acc'])

In [205]:
print(X_train.shape)

(618, 27)


In [206]:
print(X_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [207]:
print(Y_train)

[[1 0 1 1 1 0]
 [1 1 0 1 0 0]
 [1 0 1 1 1 1]
 ...
 [1 0 1 1 0 1]
 [1 0 1 0 0 1]
 [1 0 0 1 1 0]]


In [0]:
decrypter_X_train = Y_train
decrypter_Y_train = X_train

In [209]:
print(decrypter_X_train.shape)
print(decrypter_Y_train.shape)

(618, 6)
(618, 27)


In [0]:
checkpoint = ModelCheckpoint('/content/denrypt_1.h5', monitor = 'val_loss', verbose = 1, save_best_only = True, save_weights_only = True)
reducelr = ReduceLROnPlateau(monitor = 'val_loss', verbose = 1, patience = 5,factor = 0.05, min_lr = 0.003)

In [211]:
decrypter_history = decrypter.fit(decrypter_X_train, decrypter_Y_train,
                              batch_size = None,
                              epochs = epochs, verbose = 1,
                              callbacks = [checkpoint,TensorBoardColabCallback(tbc), reducelr],
                              validation_split = 0.1)

Train on 556 samples, validate on 62 samples
Epoch 1/500
556/556 [==============================] - 0s 423us/step - loss: 0.0404 - acc: 0.2536 - val_loss: 0.0332 - val_acc: 0.5000

Epoch 00001: val_loss improved from inf to 0.03316, saving model to /content/denrypt_1.h5
Epoch 2/500
556/556 [==============================] - 0s 118us/step - loss: 0.0270 - acc: 0.5540 - val_loss: 0.0227 - val_acc: 0.6774

Epoch 00002: val_loss improved from 0.03316 to 0.02273, saving model to /content/denrypt_1.h5
Epoch 3/500
556/556 [==============================] - 0s 121us/step - loss: 0.0211 - acc: 0.7986 - val_loss: 0.0195 - val_acc: 0.7903

Epoch 00003: val_loss improved from 0.02273 to 0.01947, saving model to /content/denrypt_1.h5
Epoch 4/500
556/556 [==============================] - 0s 121us/step - loss: 0.0175 - acc: 0.8741 - val_loss: 0.0149 - val_acc: 0.9516

Epoch 00004: val_loss improved from 0.01947 to 0.01491, saving model to /content/denrypt_1.h5
Epoch 5/500
556/556 [==================

In [0]:
decrypted_text = decrypter.predict(decrypter_X_train)

In [0]:
decrypted_int_text = change_output(decrypted_text)

In [214]:
print(decrypted_text[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0.]


In [215]:
print(decrypted_int_text[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0.]


In [177]:
print(decrypter_Y_train[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0.]


In [175]:
print(np.argmax(decrypted_text[0]))

19


In [174]:
print(np.argmax(decrypter_Y_train[0]))

19


In [180]:
print(decrypted_text[1])

[-1.0690315e-02  6.7433417e-03 -3.3332820e-03 -2.6592540e-04
 -3.4917467e-03 -1.1001769e-02 -2.5728755e-03 -1.6421095e-02
 -8.8299112e-03 -9.1702939e-04 -1.6151443e-02 -3.1508247e-03
  5.1639993e-03  9.8918474e-01  3.8326979e-03 -1.8503532e-03
 -4.1215606e-03 -7.0170132e-03 -3.0963824e-03 -8.4693031e-03
 -6.1515705e-03  1.5306547e-02 -4.4512823e-03 -3.4247430e-03
 -3.0064145e-03 -5.5271345e-03  1.6937867e-02]


In [183]:
print(decrypted_int_text[1])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0.]


In [179]:
print(decrypter_Y_train[1])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0.]


In [171]:
print(np.argmax(decrypted_text[1]))

13


In [172]:
print(np.argmax(decrypter_Y_train[1]))

13


In [184]:
accuracy(decrypted_int_text, decrypter_Y_train)

Accuracy for the given batch is : 100.0  % 
